---

- name: Copy general shellrc file
  ansible.builtin.copy:
    src: shellrc.generic
    dest: ~/.shellrc.generic

- name: Check if zsh is installed
  ansible.builtin.command: which zsh
  register: zsh_path
  failed_when: false

- name: Copy zsh configuration file
  ansible.builtin.copy:
    src: zshrc
    dest: ~/.zshrc
  when: zsh_path.rc == 0

- name: Check if bash is installed
  ansible.builtin.command: which bash
  register: bash_path
  failed_when: false

- name: Copy bash configuration file
  ansible.builtin.copy:
    src: bashrc
    dest: ~/.bashrc
  when: bash_path.rc == 0

- name: Check if nu is installed
  ansible.builtin.command: which nu
  register: nu_path
  failed_when: false

- name: Copy nu configuration
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: ~/.config/nushell/
  when: nu_path.rc == 0
  loop:
    - nu/config.nu
    - nu/env.nu

- name: Add custom config.nu configuration
  ansible.builtin.blockinfile:
    path: ~/.config/nushell/config.nu
    block: "{{ config.shells.nu.config }}"
  when: nu_path.rc == 0 and config.shells.nu.config is defined

- name: Add custom env.nu configuration
  ansible.builtin.blockinfile:
    path: ~/.config/nushell/env.nu
    block: "{{ config.shells.nu.env }}"
  when: nu_path.rc == 0 and config.shells.nu.env is defined

- name: Install starship
  ansible.builtin.command: curl -sS https://starship.rs/install.sh | sh -s -- -y -b ~/.local/bin
  failed_when: false
  args:
    warn: false
