---

- name: Copy general shellrc file
  ansible.builtin.copy:
    src: shellrc.generic
    dest: ~/.shellrc.generic

- name: Check if zsh is installed
  ansible.builtin.command: which zsh
  register: zsh_path
  failed_when: false

- name: Copy zsh configuration file
  ansible.builtin.copy:
    src: zshrc
    dest: ~/.zshrc
  when: zsh_path.rc == 0

- name: Add custom zsh configuration
  ansible.builtin.blockinfile:
    path: ~/.zshrc
    block: "{{ config.shells.zsh.rc }}"
  when: zsh_path.rc == 0 and config.shells.zsh.rc is defined

- name: Check if bash is installed
  ansible.builtin.command: which bash
  register: bash_path
  failed_when: false

- name: Copy bash configuration file
  ansible.builtin.copy:
    src: bashrc
    dest: ~/.bashrc
  when: bash_path.rc == 0

- name: Add custom bash configuration
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    block: "{{ config.shells.bash.rc }}"
  when: bash_path.rc == 0 and config.shells.bash.rc is defined

- name: Check if nu is installed
  ansible.builtin.command: which nu
  register: nu_path
  failed_when: false

- name: Copy nu configuration
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: ~/.config/nushell/
  when: nu_path.rc == 0
  loop:
    - nu/config.nu
    - nu/env.nu

- name: Add custom config.nu configuration
  ansible.builtin.blockinfile:
    path: ~/.config/nushell/config.nu
    block: "{{ config.shells.nu.config }}"
  when: nu_path.rc == 0 and config.shells.nu.config is defined

- name: Add custom env.nu configuration
  ansible.builtin.blockinfile:
    path: ~/.config/nushell/env.nu
    block: "{{ config.shells.nu.env }}"
  when: nu_path.rc == 0 and config.shells.nu.env is defined

- name: Download Starship.rs install script
  get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/install_starship.sh
    mode: '0755'
  environment:
    - http_proxy: "{{ proxy | default('') }}"
    - https_proxy: "{{ proxy | default('') }}"
    - ftp_proxy: "{{ proxy | default('') }}"
  ignore_errors: true
  register: download_starship

- name: Execute Starship.rs install script
  ansible.builtin.command: /tmp/install_starship.sh -y -b ~/.local/bin
  ignore_errors: true
  when: download_starship is succeeded

- name: Remove the downloaded script
  ansible.builtin.file:
    path: /tmp/install_starship.sh
    state: absent
  when: download_starship is succeeded

- name: Setup rc script for ssh
  ansible.builtin.copy:
    src: ssh_rc
    dest: ~/.ssh/rc
