#!/bin/sh

LINK=~/.ssh/ssh_auth_sock

if [ ! -S "$LINK" ] && [ -S "$SSH_AUTH_SOCK" ]; then
    ln -sf $SSH_AUTH_SOCK "$LINK"
fi

# example sshrc file
if read proto cookie && [ -n "$DISPLAY" ]; then
         if [ `echo $DISPLAY | cut -c1-10` = 'localhost:' ]; then
                 # X11UseLocalhost=yes
                 echo add unix:`echo $DISPLAY |
                     cut -c11-` $proto $cookie
         else
                 # X11UseLocalhost=no
                 echo add $DISPLAY $proto $cookie
         fi | xauth -q -
fi
