- name: Dotfiles configuration
  hosts: localhost
  connection: local
  tasks:
    - name: Install fonts
      ansible.builtin.include_tasks:
        file: fonts/setup.yml
    - name: Install rust tools
      ansible.builtin.include_tasks:
        file: rust/setup.yml
    - name: Configure shells
      ansible.builtin.include_tasks:
        file: shells/setup.yml
    - name: Configure terminals
      ansible.builtin.include_tasks:
        file: terminals/setup.yml
    - name: Configure editors
      ansible.builtin.include_tasks:
        file: editors/setup.yml
    - name: Configure terminal multiplexers
      ansible.builtin.include_tasks:
        file: term_multiplexers/setup.yml
    - name: Configure git
      ansible.builtin.include_tasks:
        file: git/setup.yml
    - name: Uninstall lazygit
      ansible.builtin.command: find "${HOME}" -type f -not -path "*/*dotfiles*/*" -name "*lazygit*" -exec rm {} + 2> /dev/null
    - name: Remove nvim
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
        force: true
        recurse: true
      loop:
        - ~/.config/nvim
        - ~/.cache/nvim
        - ~/.local/share/nvim
