- name: Dotfiles configuration
  hosts: all
  tasks:
    - name: Install fonts
      ansible.builtin.include_tasks:
        file: fonts/setup.yml
    - name: Install rust tools
      ansible.builtin.include_tasks:
        file: rust/setup.yml
    - name: Configure shells
      ansible.builtin.include_tasks:
        file: shells/setup.yml
    - name: Configure terminals
      ansible.builtin.include_tasks:
        file: terminals/setup.yml
    - name: Configure editors
      ansible.builtin.include_tasks:
        file: editors/setup.yml
    - name: Configure terminal multiplexers
      ansible.builtin.include_tasks:
        file: term_multiplexers/setup.yml
    - name: Configure git
      ansible.builtin.include_tasks:
        file: git/setup.yml
    - name: Remove nvim
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
        force: true
      loop:
        - ~/.config/nvim/
        - ~/.cache/nvim/
        - ~/.local/share/nvim/
        - ~/.config/nvim
        - ~/.cache/nvim
        - ~/.local/share/nvim
    - name: Uninstall lazygit
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/bin/lazygit"
        state: absent
        force: true
    - name: Find cargo compile directories
      ansible.builtin.find:
        paths: /tmp
        file_type: directory
        use_regex: true
        patterns: "cargo-install.*"
      register: found_files
    - name: Delete cargo compile directories
      ansible.builtin.file:
        state: absent
        path: "{{ item.path }}"
      when: item.pw_name == lookup('ansible.builtin.env', 'USER')
      loop: "{{ found_files.files }}"
