---

- name: Check if rust tools can be installed
  ansible.builtin.find:
    paths:
      - /usr/bin
      - /usr/local/bin
      - ~/.cargo/bin
    patterns: cargo
    recurse: true
  register: cargo_paths

- name: Install tools with cargo
  ansible.builtin.command: "{{ cargo_paths['files'][0]['path'] }} install {{ item }}"
  failed_when: false
  with_items:
    - zellij
    - cargo-info
    - cargo-add
    - cargo-update
    - gitui
    - bat
    - tokei
    - zoxide
    - nu
  when: cargo_paths['files']

- name: Install rust aliases
  include_tasks: alias_install.yml
  loop:
    - name: exa
      alias: ls
      alias_call: exa --icons
    - name: ripgrep
      alias: grep
      alias_call: rg
    - name: xcp
      alias: cp
      alias_call: xcp
  loop_control:
    loop_var: tool
  when: cargo_paths['files']
