theme = "rose_pine_dawn"

[editor]
line-number = "relative"
true-color = true
idle-timeout = 100
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

[keys.normal."+"]
d = ":insert-output date +'%a, %d.%m.%Y'"
